# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "k8snode1" do |k8snode1|
    k8snode1.vm.box = "centos/7"
    k8snode1.vm.hostname = "k8snode1"
    k8snode1.vm.network "private_network", ip: "10.0.4.15"

    k8snode1.vm.provision "shell", inline: <<-SHELL
    	echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD1j1A0g7ebdghBy2UX+baArSx9jzYGTS5HwqyKEniRZ49wc/P20v5HLboCW+pzf3W8GYN3wAN2yTgxczydBO30bXAFhmAwsv/WI43kPRHLlgswSTV7KZcChqc//IsLi74LDY2kxpxcfQZG4uD3ZijsATbyZYO1atBcG5o2Ufobu0FQpSAh9F7eR0mtXzMa2XA2Mt8OlWkzmM3Oz/ORdAPqt9AMLIDk5jiCsBF8qEkLvDHtgU2MwWE6JywbdEYwQ+c6cB17LnJHaoNjOnQ/6z/YLV0TBnXeDO+SwW5dm36IPC9bulBqy4q/mo9cV3Ml3qOT41HsA2fRG8FxXpMum5aD OpenSSH-rsa-import-101417" >> /home/vagrant/.ssh/authorized_keys
      sudo yum update -y
  	SHELL
  end

  config.vm.define "k8snode2" do |k8snode2|
    k8snode2.vm.box = "centos/7"
    k8snode2.vm.hostname = "k8snode2"
    k8snode2.vm.network "private_network", ip: "10.0.4.16"

    k8snode2.vm.provision "shell", inline: <<-SHELL
    	echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD1j1A0g7ebdghBy2UX+baArSx9jzYGTS5HwqyKEniRZ49wc/P20v5HLboCW+pzf3W8GYN3wAN2yTgxczydBO30bXAFhmAwsv/WI43kPRHLlgswSTV7KZcChqc//IsLi74LDY2kxpxcfQZG4uD3ZijsATbyZYO1atBcG5o2Ufobu0FQpSAh9F7eR0mtXzMa2XA2Mt8OlWkzmM3Oz/ORdAPqt9AMLIDk5jiCsBF8qEkLvDHtgU2MwWE6JywbdEYwQ+c6cB17LnJHaoNjOnQ/6z/YLV0TBnXeDO+SwW5dm36IPC9bulBqy4q/mo9cV3Ml3qOT41HsA2fRG8FxXpMum5aD OpenSSH-rsa-import-101417" >> /home/vagrant/.ssh/authorized_keys
      sudo yum update -y
  	SHELL
  end

  config.vm.define "k8snode3" do |k8snode3|
    k8snode3.vm.box = "centos/7"
    k8snode3.vm.hostname = "k8snode3"
    k8snode3.vm.network "private_network", ip: "10.0.4.18"

    k8snode3.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD1j1A0g7ebdghBy2UX+baArSx9jzYGTS5HwqyKEniRZ49wc/P20v5HLboCW+pzf3W8GYN3wAN2yTgxczydBO30bXAFhmAwsv/WI43kPRHLlgswSTV7KZcChqc//IsLi74LDY2kxpxcfQZG4uD3ZijsATbyZYO1atBcG5o2Ufobu0FQpSAh9F7eR0mtXzMa2XA2Mt8OlWkzmM3Oz/ORdAPqt9AMLIDk5jiCsBF8qEkLvDHtgU2MwWE6JywbdEYwQ+c6cB17LnJHaoNjOnQ/6z/YLV0TBnXeDO+SwW5dm36IPC9bulBqy4q/mo9cV3Ml3qOT41HsA2fRG8FxXpMum5aD OpenSSH-rsa-import-101417" >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "k8smaster" do |k8smaster|
    k8smaster.vm.box = "centos/7"
    k8smaster.vm.hostname = "k8smaster"
    k8smaster.vm.network "private_network", ip: "10.0.4.17"

    k8smaster.vm.provision "shell", inline: <<-SHELL
    	echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD1j1A0g7ebdghBy2UX+baArSx9jzYGTS5HwqyKEniRZ49wc/P20v5HLboCW+pzf3W8GYN3wAN2yTgxczydBO30bXAFhmAwsv/WI43kPRHLlgswSTV7KZcChqc//IsLi74LDY2kxpxcfQZG4uD3ZijsATbyZYO1atBcG5o2Ufobu0FQpSAh9F7eR0mtXzMa2XA2Mt8OlWkzmM3Oz/ORdAPqt9AMLIDk5jiCsBF8qEkLvDHtgU2MwWE6JywbdEYwQ+c6cB17LnJHaoNjOnQ/6z/YLV0TBnXeDO+SwW5dm36IPC9bulBqy4q/mo9cV3Ml3qOT41HsA2fRG8FxXpMum5aD OpenSSH-rsa-import-101417" >> /home/vagrant/.ssh/authorized_keys
      sudo yum update -y
  	SHELL
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
