---
  - name: add k8s repo
    copy:
      src: files/kubernetes.repo
      dest: /etc/yum.repos.d/

  - name: add bridged traffic
    copy:
      src: files/k8s.conf
      dest: /etc/sysctl.d/k8s.conf

  - name: reload sysctl
    shell: sysctl --system

  - name: install k8s paks
    yum:
      name:
        - kubeadm
        - kubelet
        - kubectl
      state: latest
      disable_excludes: 'kubernetes'

  - name: Make sure a kubelet service is running
    systemd:
      state: started
      name: kubelet
      enabled: yes
